---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
spec:
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
  selector:
    app.kubernetes.io/component: "brain"
