apiVersion: edge.cattle.io/v1alpha1
kind: DeviceLink
metadata:
  name: nginx-devices
spec:
  adaptor:
    node: edge-worker
    name: adaptors.edge.cattle.io/agent-device
  model:
    apiVersion: "devices.edge.cattle.io/v1alpha1"
    kind: "AgentDeviceGroup"
  template:
    metadata:
      labels:
        device: ip-172-31-31-2
    spec:
      deleteNodes: false
      apps:
        - name: nginx
          namespace: default
          template:
            metadata:
              labels:
                device: ip-172-31-31-2
            spec:
              containers:
                - name: nginx
                  image: nginx:1.14.2
                  ports:
                    - containerPort: 80