# keep the service name as same
nameReference:
  - kind: Namespace
    version: v1
    fieldSpecs:
      - kind: MutatingWebhookConfiguration
        group: admissionregistration.k8s.io
        path: webhooks/clientConfig/service/name
      - kind: ValidatingWebhookConfiguration
        group: admissionregistration.k8s.io
        path: webhooks/clientConfig/service/name
      - kind: CustomResourceDefinition
        group: apiextensions.k8s.io
        path: spec/conversion/webhookClientConfig/service/name
