# keep the service name as same
nameReference:
  - kind: Service
    version: v1
    fieldSpecs:
      - kind: MutatingWebhookConfiguration
        group: admissionregistration.k8s.io
        path: webhooks/clientConfig/service/name
      - kind: ValidatingWebhookConfiguration
        group: admissionregistration.k8s.io
        path: webhooks/clientConfig/service/name
      - kind: CustomResourceDefinition
        group: apiextensions.k8s.io
        path: spec/conversion/webhook/clientConfig/service/name
  - kind: Namespace
    version: v1
    fieldSpecs:
      - kind: MutatingWebhookConfiguration
        group: admissionregistration.k8s.io
        path: webhooks/clientConfig/service/namespace
      - kind: ValidatingWebhookConfiguration
        group: admissionregistration.k8s.io
        path: webhooks/clientConfig/service/namespace
      - kind: CustomResourceDefinition
        group: apiextensions.k8s.io
        path: spec/conversion/webhook/clientConfig/service/namespace
  - kind: Issuer
    group: cert-manager.io
    fieldSpecs:
      - kind: Certificate
        group: cert-manager.io
        path: spec/issuerRef/name

# confirm the namespace has been created or not
namespace:
  - kind: MutatingWebhookConfiguration
    group: admissionregistration.k8s.io
    path: webhooks/clientConfig/service/namespace
    create: true
  - kind: ValidatingWebhookConfiguration
    group: admissionregistration.k8s.io
    path: webhooks/clientConfig/service/namespace
    create: true
  - kind: CustomResourceDefinition
    group: apiextensions.k8s.io
    path: spec/conversion/webhook/clientConfig/service/namespace
    create: true

# indicate the vars placeholder when substituting
varReference:
  - path: metadata/annotations
  - kind: Certificate
    group: cert-manager.io
    path: spec/commonName
  - kind: Certificate
    group: cert-manager.io
    path: spec/dnsNames