---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/component: "token-reader"
  name: token-reader
  namespace: system
spec:
  securityContext:
    runAsUser: 0
  restartPolicy: OnFailure
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                  - "true"
  containers:
    - name: token-reader
      image: bitnami/kubectl
      command: ["/bin/sh"]
      args: ["-c","kubectl get secret node-token; if [ $? -ne 0 ]; then kubectl create secret generic node-token --from-file=/var/lib/rancher/k3s/server/node-token; fi"]
      volumeMounts:
        - mountPath: /var/lib/rancher/k3s/server/node-token
          name: token
  tolerations:
    - operator: Exists
  volumes:
    - name: token
      hostPath:
        path: /var/lib/rancher/k3s/server/node-token
        type: File