
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - devices.edge.cattle.io
  resources:
  - dummyprotocoldevices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devices.edge.cattle.io
  resources:
  - dummyprotocoldevices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - devices.edge.cattle.io
  resources:
  - dummyspecialdevices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devices.edge.cattle.io
  resources:
  - dummyspecialdevices/status
  verbs:
  - get
  - patch
  - update
