// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MqttConfig) DeepCopyInto(out *MqttConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MqttConfig.
func (in *MqttConfig) DeepCopy() *MqttConfig {
	if in == nil {
		return nil
	}
	out := new(MqttConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MqttDevice) DeepCopyInto(out *MqttDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MqttDevice.
func (in *MqttDevice) DeepCopy() *MqttDevice {
	if in == nil {
		return nil
	}
	out := new(MqttDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MqttDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MqttDeviceList) DeepCopyInto(out *MqttDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MqttDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MqttDeviceList.
func (in *MqttDeviceList) DeepCopy() *MqttDeviceList {
	if in == nil {
		return nil
	}
	out := new(MqttDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MqttDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MqttDeviceSpec) DeepCopyInto(out *MqttDeviceSpec) {
	*out = *in
	out.Config = in.Config
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]Property, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MqttDeviceSpec.
func (in *MqttDeviceSpec) DeepCopy() *MqttDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(MqttDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MqttDeviceStatus) DeepCopyInto(out *MqttDeviceStatus) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]StatusProperty, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MqttDeviceStatus.
func (in *MqttDeviceStatus) DeepCopy() *MqttDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(MqttDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Property) DeepCopyInto(out *Property) {
	*out = *in
	out.SubInfo = in.SubInfo
	out.PubInfo = in.PubInfo
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Property.
func (in *Property) DeepCopy() *Property {
	if in == nil {
		return nil
	}
	out := new(Property)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PubInfo) DeepCopyInto(out *PubInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PubInfo.
func (in *PubInfo) DeepCopy() *PubInfo {
	if in == nil {
		return nil
	}
	out := new(PubInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusProperty) DeepCopyInto(out *StatusProperty) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
	in.UpdatedAt.DeepCopyInto(&out.UpdatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusProperty.
func (in *StatusProperty) DeepCopy() *StatusProperty {
	if in == nil {
		return nil
	}
	out := new(StatusProperty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubInfo) DeepCopyInto(out *SubInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubInfo.
func (in *SubInfo) DeepCopy() *SubInfo {
	if in == nil {
		return nil
	}
	out := new(SubInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueArrayProps) DeepCopyInto(out *ValueArrayProps) {
	*out = *in
	in.ValueProps.DeepCopyInto(&out.ValueProps)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueArrayProps.
func (in *ValueArrayProps) DeepCopy() *ValueArrayProps {
	if in == nil {
		return nil
	}
	out := new(ValueArrayProps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueFloat) DeepCopyInto(out *ValueFloat) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueFloat.
func (in *ValueFloat) DeepCopy() *ValueFloat {
	if in == nil {
		return nil
	}
	out := new(ValueFloat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueProps) DeepCopyInto(out *ValueProps) {
	*out = *in
	if in.FloatValue != nil {
		in, out := &in.FloatValue, &out.FloatValue
		*out = new(ValueFloat)
		**out = **in
	}
	if in.ArrayValue != nil {
		in, out := &in.ArrayValue, &out.ArrayValue
		*out = make([]ValueArrayProps, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ObjectValue != nil {
		in, out := &in.ObjectValue, &out.ObjectValue
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueProps.
func (in *ValueProps) DeepCopy() *ValueProps {
	if in == nil {
		return nil
	}
	out := new(ValueProps)
	in.DeepCopyInto(out)
	return out
}
