// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDevice) DeepCopyInto(out *MQTTDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDevice.
func (in *MQTTDevice) DeepCopy() *MQTTDevice {
	if in == nil {
		return nil
	}
	out := new(MQTTDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDeviceList) DeepCopyInto(out *MQTTDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDeviceList.
func (in *MQTTDeviceList) DeepCopy() *MQTTDeviceList {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDeviceProperty) DeepCopyInto(out *MQTTDeviceProperty) {
	*out = *in
	in.MQTTMessagePayloadOptions.DeepCopyInto(&out.MQTTMessagePayloadOptions)
	in.MQTTMessageTopicOperation.DeepCopyInto(&out.MQTTMessageTopicOperation)
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(MQTTDevicePropertyValue)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDeviceProperty.
func (in *MQTTDeviceProperty) DeepCopy() *MQTTDeviceProperty {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceProperty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDevicePropertyValue) DeepCopyInto(out *MQTTDevicePropertyValue) {
	*out = *in
	if in.Raw != nil {
		in, out := &in.Raw, &out.Raw
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDevicePropertyValue.
func (in *MQTTDevicePropertyValue) DeepCopy() *MQTTDevicePropertyValue {
	if in == nil {
		return nil
	}
	out := new(MQTTDevicePropertyValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDeviceProtocol) DeepCopyInto(out *MQTTDeviceProtocol) {
	*out = *in
	in.MQTTOptions.DeepCopyInto(&out.MQTTOptions)
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(MQTTDeviceSchema)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDeviceProtocol.
func (in *MQTTDeviceProtocol) DeepCopy() *MQTTDeviceProtocol {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceProtocol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDeviceSchema) DeepCopyInto(out *MQTTDeviceSchema) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDeviceSchema.
func (in *MQTTDeviceSchema) DeepCopy() *MQTTDeviceSchema {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDeviceSpec) DeepCopyInto(out *MQTTDeviceSpec) {
	*out = *in
	in.Protocol.DeepCopyInto(&out.Protocol)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]MQTTDeviceProperty, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDeviceSpec.
func (in *MQTTDeviceSpec) DeepCopy() *MQTTDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDeviceStatus) DeepCopyInto(out *MQTTDeviceStatus) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]MQTTDeviceStatusProperty, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDeviceStatus.
func (in *MQTTDeviceStatus) DeepCopy() *MQTTDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDeviceStatusProperty) DeepCopyInto(out *MQTTDeviceStatusProperty) {
	*out = *in
	in.MQTTDeviceProperty.DeepCopyInto(&out.MQTTDeviceProperty)
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDeviceStatusProperty.
func (in *MQTTDeviceStatusProperty) DeepCopy() *MQTTDeviceStatusProperty {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceStatusProperty)
	in.DeepCopyInto(out)
	return out
}
