// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/rancher/octopus/api/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTClientBasicAuth) DeepCopyInto(out *MQTTClientBasicAuth) {
	*out = *in
	if in.UsernameRef != nil {
		in, out := &in.UsernameRef, &out.UsernameRef
		*out = new(apiv1alpha1.DeviceLinkReferenceRelationship)
		**out = **in
	}
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(apiv1alpha1.DeviceLinkReferenceRelationship)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTClientBasicAuth.
func (in *MQTTClientBasicAuth) DeepCopy() *MQTTClientBasicAuth {
	if in == nil {
		return nil
	}
	out := new(MQTTClientBasicAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTClientOptions) DeepCopyInto(out *MQTTClientOptions) {
	*out = *in
	if in.ProtocolVersion != nil {
		in, out := &in.ProtocolVersion, &out.ProtocolVersion
		*out = new(uint)
		**out = **in
	}
	if in.Will != nil {
		in, out := &in.Will, &out.Will
		*out = new(MQTTClientWillMessage)
		(*in).DeepCopyInto(*out)
	}
	if in.BasicAuth != nil {
		in, out := &in.BasicAuth, &out.BasicAuth
		*out = new(MQTTClientBasicAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.TLSConfig != nil {
		in, out := &in.TLSConfig, &out.TLSConfig
		*out = new(MQTTClientTLS)
		(*in).DeepCopyInto(*out)
	}
	if in.CleanSession != nil {
		in, out := &in.CleanSession, &out.CleanSession
		*out = new(bool)
		**out = **in
	}
	if in.Store != nil {
		in, out := &in.Store, &out.Store
		*out = new(MQTTClientStore)
		**out = **in
	}
	if in.ResumeSubs != nil {
		in, out := &in.ResumeSubs, &out.ResumeSubs
		*out = new(bool)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.KeepAlive != nil {
		in, out := &in.KeepAlive, &out.KeepAlive
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PingTimeout != nil {
		in, out := &in.PingTimeout, &out.PingTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = new(bool)
		**out = **in
	}
	if in.WriteTimeout != nil {
		in, out := &in.WriteTimeout, &out.WriteTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.AutoReconnect != nil {
		in, out := &in.AutoReconnect, &out.AutoReconnect
		*out = new(bool)
		**out = **in
	}
	if in.MaxReconnectInterval != nil {
		in, out := &in.MaxReconnectInterval, &out.MaxReconnectInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MessageChannelDepth != nil {
		in, out := &in.MessageChannelDepth, &out.MessageChannelDepth
		*out = new(uint)
		**out = **in
	}
	if in.HTTPHeaders != nil {
		in, out := &in.HTTPHeaders, &out.HTTPHeaders
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTClientOptions.
func (in *MQTTClientOptions) DeepCopy() *MQTTClientOptions {
	if in == nil {
		return nil
	}
	out := new(MQTTClientOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTClientOptionsStatus) DeepCopyInto(out *MQTTClientOptionsStatus) {
	*out = *in
	if in.ProtocolVersion != nil {
		in, out := &in.ProtocolVersion, &out.ProtocolVersion
		*out = new(uint)
		**out = **in
	}
	if in.Will != nil {
		in, out := &in.Will, &out.Will
		*out = new(MQTTClientWillMessageStatus)
		**out = **in
	}
	if in.CleanSession != nil {
		in, out := &in.CleanSession, &out.CleanSession
		*out = new(bool)
		**out = **in
	}
	out.Store = in.Store
	if in.ResumeSubs != nil {
		in, out := &in.ResumeSubs, &out.ResumeSubs
		*out = new(bool)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.KeepAlive != nil {
		in, out := &in.KeepAlive, &out.KeepAlive
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PingTimeout != nil {
		in, out := &in.PingTimeout, &out.PingTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = new(bool)
		**out = **in
	}
	if in.WriteTimeout != nil {
		in, out := &in.WriteTimeout, &out.WriteTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.AutoReconnect != nil {
		in, out := &in.AutoReconnect, &out.AutoReconnect
		*out = new(bool)
		**out = **in
	}
	if in.MaxReconnectInterval != nil {
		in, out := &in.MaxReconnectInterval, &out.MaxReconnectInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MessageChannelDepth != nil {
		in, out := &in.MessageChannelDepth, &out.MessageChannelDepth
		*out = new(uint)
		**out = **in
	}
	if in.HTTPHeaders != nil {
		in, out := &in.HTTPHeaders, &out.HTTPHeaders
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTClientOptionsStatus.
func (in *MQTTClientOptionsStatus) DeepCopy() *MQTTClientOptionsStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTClientOptionsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTClientTLS) DeepCopyInto(out *MQTTClientTLS) {
	*out = *in
	if in.CAFilePEMRef != nil {
		in, out := &in.CAFilePEMRef, &out.CAFilePEMRef
		*out = new(apiv1alpha1.DeviceLinkReferenceRelationship)
		**out = **in
	}
	if in.CertFilePEMRef != nil {
		in, out := &in.CertFilePEMRef, &out.CertFilePEMRef
		*out = new(apiv1alpha1.DeviceLinkReferenceRelationship)
		**out = **in
	}
	if in.KeyFilePEMRef != nil {
		in, out := &in.KeyFilePEMRef, &out.KeyFilePEMRef
		*out = new(apiv1alpha1.DeviceLinkReferenceRelationship)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTClientTLS.
func (in *MQTTClientTLS) DeepCopy() *MQTTClientTLS {
	if in == nil {
		return nil
	}
	out := new(MQTTClientTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTClientWillMessage) DeepCopyInto(out *MQTTClientWillMessage) {
	*out = *in
	if in.Topic != nil {
		in, out := &in.Topic, &out.Topic
		*out = new(MQTTMessageTopicStatic)
		**out = **in
	}
	if in.Retained != nil {
		in, out := &in.Retained, &out.Retained
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTClientWillMessage.
func (in *MQTTClientWillMessage) DeepCopy() *MQTTClientWillMessage {
	if in == nil {
		return nil
	}
	out := new(MQTTClientWillMessage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTClientWillMessageStatus) DeepCopyInto(out *MQTTClientWillMessageStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTClientWillMessageStatus.
func (in *MQTTClientWillMessageStatus) DeepCopy() *MQTTClientWillMessageStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTClientWillMessageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTMessageOptions) DeepCopyInto(out *MQTTMessageOptions) {
	*out = *in
	in.MQTTMessagePayloadOptions.DeepCopyInto(&out.MQTTMessagePayloadOptions)
	out.Topic = in.Topic
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTMessageOptions.
func (in *MQTTMessageOptions) DeepCopy() *MQTTMessageOptions {
	if in == nil {
		return nil
	}
	out := new(MQTTMessageOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTMessageOptionsStatus) DeepCopyInto(out *MQTTMessageOptionsStatus) {
	*out = *in
	out.WaitTimeout = in.WaitTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTMessageOptionsStatus.
func (in *MQTTMessageOptionsStatus) DeepCopy() *MQTTMessageOptionsStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTMessageOptionsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTMessagePayloadOptions) DeepCopyInto(out *MQTTMessagePayloadOptions) {
	*out = *in
	if in.Retained != nil {
		in, out := &in.Retained, &out.Retained
		*out = new(bool)
		**out = **in
	}
	if in.WaitTimeout != nil {
		in, out := &in.WaitTimeout, &out.WaitTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTMessagePayloadOptions.
func (in *MQTTMessagePayloadOptions) DeepCopy() *MQTTMessagePayloadOptions {
	if in == nil {
		return nil
	}
	out := new(MQTTMessagePayloadOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTOptionsSpec) DeepCopyInto(out *MQTTOptionsSpec) {
	*out = *in
	in.Client.DeepCopyInto(&out.Client)
	in.Message.DeepCopyInto(&out.Message)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTOptionsSpec.
func (in *MQTTOptionsSpec) DeepCopy() *MQTTOptionsSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTOptionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTOptionsStatus) DeepCopyInto(out *MQTTOptionsStatus) {
	*out = *in
	in.Client.DeepCopyInto(&out.Client)
	out.Message = in.Message
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTOptionsStatus.
func (in *MQTTOptionsStatus) DeepCopy() *MQTTOptionsStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTOptionsStatus)
	in.DeepCopyInto(out)
	return out
}
