# Adds namespace to all resources.
namespace: octopus-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: octopus-adaptor-opcua-

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/name: "octopus-adaptor-opcua"
  app.kubernetes.io/version: "master"

## Images to overwrite the default images.
images:
  - name: rancher/octopus-adaptor-opcua
    newName: rancher/octopus-adaptor-opcua
    newTag: master

bases:
  - ../../crd
  - ../../rbac
  - ../../workload
