apiVersion: edge.cattle.io/v1alpha1
kind: DeviceLink
metadata:
  name: kitchen-light
spec:
  adaptor:
    node: edge-worker
    name: adaptors.edge.cattle.io/mqtt
  model:
    apiVersion: "devices.edge.cattle.io/v1alpha1"
    kind: "MQTTDevice"
  template:
    metadata:
      labels:
        device: kitchen-light
    spec:
      protocol:
        pattern: "AttributedTopic"
        client:
          server: "tcp://octopus-simulator-mqtt.octopus-simulator-system:1883"
        message:
          topic: "cattle.io/octopus/home/:operator/kitchen/light/:path"
          operator:
            read: "status"
            write: "set"
      properties:
        - name: "switch"
          description: "The switch of light"
          type: "boolean"
          readOnlye: false
          qos: 2
        - name: "gear"
          description: "The gear of light"
          type: "string"
          readOnlye: false
          annotations:
            type: "enum"
            format: "low,mid,high"
          operator:
            read: "get"
            write: "control"
        - name: "power"
          path: "parameter_power"
          description: "The power of light"
          type: "float"
          annotations:
            group: "parameter"
            unit: "watt"
        - name: "luminance"
          path: "parameter_luminance"
          description: "The luminance of light"
          type: "int"
          annotations:
            group: "parameter"
            unit: "luminance"
        - name: "manufacturer"
          description: "The manufacturer of light"
          type: "string"
          annotations:
            group: "production"
        - name: "productionDate"
          path: "production_date"
          description: "The production date of light"
          type: "string"
          annotations:
            group: "production"
            type: "datetime"
            standard: "ISO 8601"
            format: "YYYY-MM-DDThh:mm:ss.SSZ"
        - name: "serviceLife"
          path: "service_life"
          description: "The service life of light"
          type: "string"
          annotations:
            group: "production"
            type: "duration"
            standard: "ISO 8601"
            format: "PYYMMDD"
