apiVersion: edge.cattle.io/v1alpha1
kind: DeviceLink
metadata:
  name: living-room-light
spec:
  adaptor:
    node: edge-worker
    name: adaptors.edge.cattle.io/mqtt
  model:
    apiVersion: "devices.edge.cattle.io/v1alpha1"
    kind: "MQTTDevice"
  template:
    metadata:
      labels:
        device: living-room-light
    spec:
      protocol:
        pattern: "AttributedTopic"
        client:
          server: "tcp://octopus-simulator-mqtt.octopus-simulator-system:1883"
        message:
          topic: "cattle.io/octopus/home/livingroom/light/:path/:operator"
          operator:
            read: ""
            write: "set"
      properties:
        - name: "switch"
          path: "switch"
          description: "The switch of light"
          type: "boolean"
          readOnly: false
        - name: "gear"
          path: "gear"
          description: "The gear of light"
          type: "string"
          readOnly: false
          annotations:
            type: "enum"
            format: "low,mid,high"
        - name: "parameter"
          path: "parameter"
          description: "The parameter information of light"
          type: "array"
        - name: "production"
          path: "production"
          description: "The production information of light"
          type: "object"
