apiVersion: edge.cattle.io/v1alpha1
kind: DeviceLink
metadata:
  name: bedroom-light
spec:
  adaptor:
    node: edge-worker
    name: adaptors.edge.cattle.io/mqtt
  model:
    apiVersion: "devices.edge.cattle.io/v1alpha1"
    kind: "MQTTDevice"
  template:
    metadata:
      labels:
        device: bedroom-light
    spec:
      protocol:
        pattern: "AttributedMessage"
        client:
          server: "tcp://test.mosquitto.org:1883"
        message:
          topic: "cattle.io/octopus/home/bedroom/light/:operator"
          operator:
            write: "set"
      properties:
        - name: "switch"
          path: "switch"
          description: "The switch of light"
          type: "boolean"
          readOnly: false
        - name: "gear"
          path: "action.gear"
          description: "The gear of light"
          type: "string"
          readOnly: false
          annotations:
            type: "enum"
            format: "low,mid,high"
        - name: "power"
          path: "parameter.power"
          description: "The power of light"
          type: "float"
          annotations:
            group: "parameter"
            unit: "watt"
        - name: "luminance"
          path: "parameter.luminance"
          description: "The luminance of light"
          type: "int"
          annotations:
            group: "parameter"
            unit: "luminance"
        - name: "manufacturer"
          path: "production.manufacturer"
          description: "The manufacturer of light"
          type: "string"
          annotations:
            group: "production"
        - name: "productionDate"
          path: "production.date"
          description: "The production date of light"
          type: "string"
          annotations:
            group: "production"
            type: "datetime"
            standard: "ISO 8601"
            format: "YYYY-MM-DDThh:mm:ss.SSZ"
        - name: "serviceLife"
          path: "production.serviceLife"
          description: "The service life of light"
          type: "string"
          annotations:
            group: "production"
            type: "duration"
            standard: "ISO 8601"
            format: "PYYMMDD"
