apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: octopus
    app.kubernetes.io/version: master
  name: octopus-simulator-system

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: mqtt
    app.kubernetes.io/name: octopus
    app.kubernetes.io/version: master
  name: octopus-simulator-mqtt
  namespace: octopus-simulator-system
spec:
  ports:
    - name: tcp
      port: 1883
      targetPort: tcp
  selector:
    app.kubernetes.io/component: mqtt
    app.kubernetes.io/name: octopus
    app.kubernetes.io/version: master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: mqtt
    app.kubernetes.io/name: octopus
    app.kubernetes.io/version: master
  name: octopus-simulator-mqtt
  namespace: octopus-simulator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: mqtt
      app.kubernetes.io/name: octopus
      app.kubernetes.io/version: master
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mqtt
        app.kubernetes.io/name: octopus
        app.kubernetes.io/version: master
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - args:
            - mqtt
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: cnrancher/octopus-simulator:master
          imagePullPolicy: Always
          name: simulator
          ports:
            - containerPort: 1883
              name: tcp
      terminationGracePeriodSeconds: 30
