// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/rancher/octopus/api/v1alpha1"
	"github.com/rancher/octopus/pkg/mqtt/api"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPCUADevice) DeepCopyInto(out *OPCUADevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPCUADevice.
func (in *OPCUADevice) DeepCopy() *OPCUADevice {
	if in == nil {
		return nil
	}
	out := new(OPCUADevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OPCUADevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPCUADeviceExtension) DeepCopyInto(out *OPCUADeviceExtension) {
	*out = *in
	if in.MQTT != nil {
		in, out := &in.MQTT, &out.MQTT
		*out = new(api.MQTTOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPCUADeviceExtension.
func (in *OPCUADeviceExtension) DeepCopy() *OPCUADeviceExtension {
	if in == nil {
		return nil
	}
	out := new(OPCUADeviceExtension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPCUADeviceList) DeepCopyInto(out *OPCUADeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OPCUADevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPCUADeviceList.
func (in *OPCUADeviceList) DeepCopy() *OPCUADeviceList {
	if in == nil {
		return nil
	}
	out := new(OPCUADeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OPCUADeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPCUADeviceParameters) DeepCopyInto(out *OPCUADeviceParameters) {
	*out = *in
	out.SyncInterval = in.SyncInterval
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPCUADeviceParameters.
func (in *OPCUADeviceParameters) DeepCopy() *OPCUADeviceParameters {
	if in == nil {
		return nil
	}
	out := new(OPCUADeviceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPCUADeviceProperty) DeepCopyInto(out *OPCUADeviceProperty) {
	*out = *in
	out.Visitor = in.Visitor
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPCUADeviceProperty.
func (in *OPCUADeviceProperty) DeepCopy() *OPCUADeviceProperty {
	if in == nil {
		return nil
	}
	out := new(OPCUADeviceProperty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPCUADevicePropertyVisitor) DeepCopyInto(out *OPCUADevicePropertyVisitor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPCUADevicePropertyVisitor.
func (in *OPCUADevicePropertyVisitor) DeepCopy() *OPCUADevicePropertyVisitor {
	if in == nil {
		return nil
	}
	out := new(OPCUADevicePropertyVisitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPCUADeviceProtocol) DeepCopyInto(out *OPCUADeviceProtocol) {
	*out = *in
	if in.BasicAuth != nil {
		in, out := &in.BasicAuth, &out.BasicAuth
		*out = new(OPCUADeviceProtocolBasicAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.TLSConfig != nil {
		in, out := &in.TLSConfig, &out.TLSConfig
		*out = new(OPCUADeviceProtocolTLS)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPCUADeviceProtocol.
func (in *OPCUADeviceProtocol) DeepCopy() *OPCUADeviceProtocol {
	if in == nil {
		return nil
	}
	out := new(OPCUADeviceProtocol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPCUADeviceProtocolBasicAuth) DeepCopyInto(out *OPCUADeviceProtocolBasicAuth) {
	*out = *in
	if in.UsernameRef != nil {
		in, out := &in.UsernameRef, &out.UsernameRef
		*out = new(apiv1alpha1.DeviceLinkReferenceRelationship)
		**out = **in
	}
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(apiv1alpha1.DeviceLinkReferenceRelationship)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPCUADeviceProtocolBasicAuth.
func (in *OPCUADeviceProtocolBasicAuth) DeepCopy() *OPCUADeviceProtocolBasicAuth {
	if in == nil {
		return nil
	}
	out := new(OPCUADeviceProtocolBasicAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPCUADeviceProtocolTLS) DeepCopyInto(out *OPCUADeviceProtocolTLS) {
	*out = *in
	if in.CertFilePEMRef != nil {
		in, out := &in.CertFilePEMRef, &out.CertFilePEMRef
		*out = new(apiv1alpha1.DeviceLinkReferenceRelationship)
		**out = **in
	}
	if in.KeyFilePEMRef != nil {
		in, out := &in.KeyFilePEMRef, &out.KeyFilePEMRef
		*out = new(apiv1alpha1.DeviceLinkReferenceRelationship)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPCUADeviceProtocolTLS.
func (in *OPCUADeviceProtocolTLS) DeepCopy() *OPCUADeviceProtocolTLS {
	if in == nil {
		return nil
	}
	out := new(OPCUADeviceProtocolTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPCUADeviceSpec) DeepCopyInto(out *OPCUADeviceSpec) {
	*out = *in
	if in.Extension != nil {
		in, out := &in.Extension, &out.Extension
		*out = new(OPCUADeviceExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(OPCUADeviceParameters)
		**out = **in
	}
	in.Protocol.DeepCopyInto(&out.Protocol)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]OPCUADeviceProperty, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPCUADeviceSpec.
func (in *OPCUADeviceSpec) DeepCopy() *OPCUADeviceSpec {
	if in == nil {
		return nil
	}
	out := new(OPCUADeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPCUADeviceStatus) DeepCopyInto(out *OPCUADeviceStatus) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]OPCUADeviceStatusProperty, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPCUADeviceStatus.
func (in *OPCUADeviceStatus) DeepCopy() *OPCUADeviceStatus {
	if in == nil {
		return nil
	}
	out := new(OPCUADeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPCUADeviceStatusProperty) DeepCopyInto(out *OPCUADeviceStatusProperty) {
	*out = *in
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPCUADeviceStatusProperty.
func (in *OPCUADeviceStatusProperty) DeepCopy() *OPCUADeviceStatusProperty {
	if in == nil {
		return nil
	}
	out := new(OPCUADeviceStatusProperty)
	in.DeepCopyInto(out)
	return out
}
