apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: octopus
    app.kubernetes.io/version: master
  name: octopus-simulator-system

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: "ble"
  name: ble
  namespace: system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: "ble"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "ble"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - name: simulator
          args:
            - ble
          env:
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.nodeName
          image: cnrancher/octopus-simulator:master
          imagePullPolicy: Always
      hostNetwork: true
      tolerations:
        - operator: Exists
      terminationGracePeriodSeconds: 30
