apiVersion: edge.cattle.io/v1alpha1
kind: DeviceLink
metadata:
  name: opcua-open
spec:
  adaptor:
    node: edge-worker
    name: adaptors.edge.cattle.io/opcua
  model:
    apiVersion: "devices.edge.cattle.io/v1alpha1"
    kind: "OPCUADevice"
  template:
    metadata:
      labels:
        device: opcua-open
    spec:
      parameters:
        syncInterval: 10s
        timeout: 10s
      extension:
        mqtt:
          client:
            server: tcp://test.mosquitto.org:1883
          message:
            # uses dynamic topic with namespaced name
            topic: "cattle.io/octopus/:namespace/:name"
      protocol:
        endpoint: opc.tcp://192.168.64.5:30839/
      properties:
        - name: datetime
          description: the current datetime
          readOnly: true
          visitor:
            nodeID: ns=0;i=2258
          type: datetime
        - name: integer
          description: mock number. Default value is 42
          readOnly: false
          visitor:
            nodeID: ns=1;s=the.answer
          type: int32
          value: "1"
        - name: string
          description: mock byte string. Default value is "test123"
          readOnly: false
          visitor:
            nodeID: ns=1;s=myByteString
          type: byteString
          value: "newString"
