apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: octopus
    app.kubernetes.io/version: master
  name: octopus-simulator-system

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: opcua
    app.kubernetes.io/name: octopus
    app.kubernetes.io/version: master
  name: octopus-simulator-opcua
  namespace: octopus-simulator-system
spec:
  ports:
    - name: tcp
      port: 4840
      targetPort: tcp
  selector:
    app.kubernetes.io/component: opcua
    app.kubernetes.io/name: octopus
    app.kubernetes.io/version: master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: opcua
    app.kubernetes.io/name: octopus
    app.kubernetes.io/version: master
  name: octopus-simulator-opcua
  namespace: octopus-simulator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: opcua
      app.kubernetes.io/name: octopus
      app.kubernetes.io/version: master
  template:
    metadata:
      labels:
        app.kubernetes.io/component: opcua
        app.kubernetes.io/name: octopus
        app.kubernetes.io/version: master
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      containers:
        - image: open62541/open62541:1.0
          name: simulator
          ports:
            - containerPort: 4840
              name: tcp
      terminationGracePeriodSeconds: 30
