---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: "brain"
  name: brain
  namespace: system
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
  selector:
    app.kubernetes.io/component: "brain"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: "brain"
  name: brain
  namespace: system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: "brain"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "brain"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - name: octopus
          args:
            - brain
            - --enable-leader-election
            - --disable-admission-webhook
          image: rancher/octopus:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: metrics
      terminationGracePeriodSeconds: 10
