
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: "brain"
  name: brain
  namespace: system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: "brain"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "brain"
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: octopus
          args:
            - brain
            - --enable-leader-election
            - --disable-admission-webhook
          image: rancher/octopus:latest
      terminationGracePeriodSeconds: 10
