// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/rancher/octopus/pkg/mqtt/api"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BluetoothDevice) DeepCopyInto(out *BluetoothDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BluetoothDevice.
func (in *BluetoothDevice) DeepCopy() *BluetoothDevice {
	if in == nil {
		return nil
	}
	out := new(BluetoothDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BluetoothDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BluetoothDeviceExtension) DeepCopyInto(out *BluetoothDeviceExtension) {
	*out = *in
	if in.MQTT != nil {
		in, out := &in.MQTT, &out.MQTT
		*out = new(api.MQTTOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BluetoothDeviceExtension.
func (in *BluetoothDeviceExtension) DeepCopy() *BluetoothDeviceExtension {
	if in == nil {
		return nil
	}
	out := new(BluetoothDeviceExtension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BluetoothDeviceList) DeepCopyInto(out *BluetoothDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BluetoothDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BluetoothDeviceList.
func (in *BluetoothDeviceList) DeepCopy() *BluetoothDeviceList {
	if in == nil {
		return nil
	}
	out := new(BluetoothDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BluetoothDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BluetoothDeviceProperty) DeepCopyInto(out *BluetoothDeviceProperty) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]BluetoothDevicePropertyAccessMode, len(*in))
		copy(*out, *in)
	}
	in.Visitor.DeepCopyInto(&out.Visitor)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BluetoothDeviceProperty.
func (in *BluetoothDeviceProperty) DeepCopy() *BluetoothDeviceProperty {
	if in == nil {
		return nil
	}
	out := new(BluetoothDeviceProperty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BluetoothDevicePropertyValueArithmeticOperation) DeepCopyInto(out *BluetoothDevicePropertyValueArithmeticOperation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BluetoothDevicePropertyValueArithmeticOperation.
func (in *BluetoothDevicePropertyValueArithmeticOperation) DeepCopy() *BluetoothDevicePropertyValueArithmeticOperation {
	if in == nil {
		return nil
	}
	out := new(BluetoothDevicePropertyValueArithmeticOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BluetoothDevicePropertyVisitor) DeepCopyInto(out *BluetoothDevicePropertyVisitor) {
	*out = *in
	if in.ArithmeticOperations != nil {
		in, out := &in.ArithmeticOperations, &out.ArithmeticOperations
		*out = make([]BluetoothDevicePropertyValueArithmeticOperation, len(*in))
		copy(*out, *in)
	}
	if in.ArithmeticOperationPrecision != nil {
		in, out := &in.ArithmeticOperationPrecision, &out.ArithmeticOperationPrecision
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BluetoothDevicePropertyVisitor.
func (in *BluetoothDevicePropertyVisitor) DeepCopy() *BluetoothDevicePropertyVisitor {
	if in == nil {
		return nil
	}
	out := new(BluetoothDevicePropertyVisitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BluetoothDeviceProtocol) DeepCopyInto(out *BluetoothDeviceProtocol) {
	*out = *in
	out.ScanTimeout = in.ScanTimeout
	out.ConnectTimeout = in.ConnectTimeout
	if in.ConnectionMTU != nil {
		in, out := &in.ConnectionMTU, &out.ConnectionMTU
		*out = new(int)
		**out = **in
	}
	out.SyncInterval = in.SyncInterval
	if in.AutoReconnect != nil {
		in, out := &in.AutoReconnect, &out.AutoReconnect
		*out = new(bool)
		**out = **in
	}
	out.MaxReconnectInterval = in.MaxReconnectInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BluetoothDeviceProtocol.
func (in *BluetoothDeviceProtocol) DeepCopy() *BluetoothDeviceProtocol {
	if in == nil {
		return nil
	}
	out := new(BluetoothDeviceProtocol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BluetoothDeviceSpec) DeepCopyInto(out *BluetoothDeviceSpec) {
	*out = *in
	if in.Extension != nil {
		in, out := &in.Extension, &out.Extension
		*out = new(BluetoothDeviceExtension)
		(*in).DeepCopyInto(*out)
	}
	in.Protocol.DeepCopyInto(&out.Protocol)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]BluetoothDeviceProperty, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BluetoothDeviceSpec.
func (in *BluetoothDeviceSpec) DeepCopy() *BluetoothDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(BluetoothDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BluetoothDeviceStatus) DeepCopyInto(out *BluetoothDeviceStatus) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]BluetoothDeviceStatusProperty, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BluetoothDeviceStatus.
func (in *BluetoothDeviceStatus) DeepCopy() *BluetoothDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(BluetoothDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BluetoothDeviceStatusProperty) DeepCopyInto(out *BluetoothDeviceStatusProperty) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]BluetoothDevicePropertyAccessMode, len(*in))
		copy(*out, *in)
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BluetoothDeviceStatusProperty.
func (in *BluetoothDeviceStatusProperty) DeepCopy() *BluetoothDeviceStatusProperty {
	if in == nil {
		return nil
	}
	out := new(BluetoothDeviceStatusProperty)
	in.DeepCopyInto(out)
	return out
}
