// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/rancher/octopus/pkg/mqtt/api"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusDevice) DeepCopyInto(out *ModbusDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusDevice.
func (in *ModbusDevice) DeepCopy() *ModbusDevice {
	if in == nil {
		return nil
	}
	out := new(ModbusDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModbusDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusDeviceExtension) DeepCopyInto(out *ModbusDeviceExtension) {
	*out = *in
	if in.MQTT != nil {
		in, out := &in.MQTT, &out.MQTT
		*out = new(api.MQTTOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusDeviceExtension.
func (in *ModbusDeviceExtension) DeepCopy() *ModbusDeviceExtension {
	if in == nil {
		return nil
	}
	out := new(ModbusDeviceExtension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusDeviceList) DeepCopyInto(out *ModbusDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModbusDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusDeviceList.
func (in *ModbusDeviceList) DeepCopy() *ModbusDeviceList {
	if in == nil {
		return nil
	}
	out := new(ModbusDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModbusDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusDeviceProperty) DeepCopyInto(out *ModbusDeviceProperty) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]ModbusDevicePropertyAccessMode, len(*in))
		copy(*out, *in)
	}
	in.Visitor.DeepCopyInto(&out.Visitor)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusDeviceProperty.
func (in *ModbusDeviceProperty) DeepCopy() *ModbusDeviceProperty {
	if in == nil {
		return nil
	}
	out := new(ModbusDeviceProperty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusDevicePropertyValueArithmeticOperation) DeepCopyInto(out *ModbusDevicePropertyValueArithmeticOperation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusDevicePropertyValueArithmeticOperation.
func (in *ModbusDevicePropertyValueArithmeticOperation) DeepCopy() *ModbusDevicePropertyValueArithmeticOperation {
	if in == nil {
		return nil
	}
	out := new(ModbusDevicePropertyValueArithmeticOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusDevicePropertyVisitor) DeepCopyInto(out *ModbusDevicePropertyVisitor) {
	*out = *in
	if in.ArithmeticOperations != nil {
		in, out := &in.ArithmeticOperations, &out.ArithmeticOperations
		*out = make([]ModbusDevicePropertyValueArithmeticOperation, len(*in))
		copy(*out, *in)
	}
	if in.ArithmeticOperationPrecision != nil {
		in, out := &in.ArithmeticOperationPrecision, &out.ArithmeticOperationPrecision
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusDevicePropertyVisitor.
func (in *ModbusDevicePropertyVisitor) DeepCopy() *ModbusDevicePropertyVisitor {
	if in == nil {
		return nil
	}
	out := new(ModbusDevicePropertyVisitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusDeviceProtocol) DeepCopyInto(out *ModbusDeviceProtocol) {
	*out = *in
	if in.RTU != nil {
		in, out := &in.RTU, &out.RTU
		*out = new(ModbusDeviceProtocolRTU)
		**out = **in
	}
	if in.TCP != nil {
		in, out := &in.TCP, &out.TCP
		*out = new(ModbusDeviceProtocolTCP)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusDeviceProtocol.
func (in *ModbusDeviceProtocol) DeepCopy() *ModbusDeviceProtocol {
	if in == nil {
		return nil
	}
	out := new(ModbusDeviceProtocol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusDeviceProtocolParameters) DeepCopyInto(out *ModbusDeviceProtocolParameters) {
	*out = *in
	out.SyncInterval = in.SyncInterval
	out.ConnectTimeout = in.ConnectTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusDeviceProtocolParameters.
func (in *ModbusDeviceProtocolParameters) DeepCopy() *ModbusDeviceProtocolParameters {
	if in == nil {
		return nil
	}
	out := new(ModbusDeviceProtocolParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusDeviceProtocolRTU) DeepCopyInto(out *ModbusDeviceProtocolRTU) {
	*out = *in
	out.ModbusDeviceProtocolParameters = in.ModbusDeviceProtocolParameters
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusDeviceProtocolRTU.
func (in *ModbusDeviceProtocolRTU) DeepCopy() *ModbusDeviceProtocolRTU {
	if in == nil {
		return nil
	}
	out := new(ModbusDeviceProtocolRTU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusDeviceProtocolTCP) DeepCopyInto(out *ModbusDeviceProtocolTCP) {
	*out = *in
	out.ModbusDeviceProtocolParameters = in.ModbusDeviceProtocolParameters
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusDeviceProtocolTCP.
func (in *ModbusDeviceProtocolTCP) DeepCopy() *ModbusDeviceProtocolTCP {
	if in == nil {
		return nil
	}
	out := new(ModbusDeviceProtocolTCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusDeviceSpec) DeepCopyInto(out *ModbusDeviceSpec) {
	*out = *in
	if in.Extension != nil {
		in, out := &in.Extension, &out.Extension
		*out = new(ModbusDeviceExtension)
		(*in).DeepCopyInto(*out)
	}
	in.Protocol.DeepCopyInto(&out.Protocol)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]ModbusDeviceProperty, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusDeviceSpec.
func (in *ModbusDeviceSpec) DeepCopy() *ModbusDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(ModbusDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusDeviceStatus) DeepCopyInto(out *ModbusDeviceStatus) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]ModbusDeviceStatusProperty, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusDeviceStatus.
func (in *ModbusDeviceStatus) DeepCopy() *ModbusDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(ModbusDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusDeviceStatusProperty) DeepCopyInto(out *ModbusDeviceStatusProperty) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]ModbusDevicePropertyAccessMode, len(*in))
		copy(*out, *in)
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusDeviceStatusProperty.
func (in *ModbusDeviceStatusProperty) DeepCopy() *ModbusDeviceStatusProperty {
	if in == nil {
		return nil
	}
	out := new(ModbusDeviceStatusProperty)
	in.DeepCopyInto(out)
	return out
}
