// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProperty) DeepCopyInto(out *DeviceProperty) {
	*out = *in
	out.Visitor = in.Visitor
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProperty.
func (in *DeviceProperty) DeepCopy() *DeviceProperty {
	if in == nil {
		return nil
	}
	out := new(DeviceProperty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusConfigRTU) DeepCopyInto(out *ModbusConfigRTU) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusConfigRTU.
func (in *ModbusConfigRTU) DeepCopy() *ModbusConfigRTU {
	if in == nil {
		return nil
	}
	out := new(ModbusConfigRTU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusConfigTCP) DeepCopyInto(out *ModbusConfigTCP) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusConfigTCP.
func (in *ModbusConfigTCP) DeepCopy() *ModbusConfigTCP {
	if in == nil {
		return nil
	}
	out := new(ModbusConfigTCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusDevice) DeepCopyInto(out *ModbusDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusDevice.
func (in *ModbusDevice) DeepCopy() *ModbusDevice {
	if in == nil {
		return nil
	}
	out := new(ModbusDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModbusDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusDeviceList) DeepCopyInto(out *ModbusDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModbusDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusDeviceList.
func (in *ModbusDeviceList) DeepCopy() *ModbusDeviceList {
	if in == nil {
		return nil
	}
	out := new(ModbusDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModbusDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusDeviceSpec) DeepCopyInto(out *ModbusDeviceSpec) {
	*out = *in
	if in.ProtocolConfig != nil {
		in, out := &in.ProtocolConfig, &out.ProtocolConfig
		*out = new(ModbusProtocolConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]DeviceProperty, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusDeviceSpec.
func (in *ModbusDeviceSpec) DeepCopy() *ModbusDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(ModbusDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusDeviceStatus) DeepCopyInto(out *ModbusDeviceStatus) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]DeviceProperty, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusDeviceStatus.
func (in *ModbusDeviceStatus) DeepCopy() *ModbusDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(ModbusDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModbusProtocolConfig) DeepCopyInto(out *ModbusProtocolConfig) {
	*out = *in
	if in.RTU != nil {
		in, out := &in.RTU, &out.RTU
		*out = new(ModbusConfigRTU)
		**out = **in
	}
	if in.TCP != nil {
		in, out := &in.TCP, &out.TCP
		*out = new(ModbusConfigTCP)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModbusProtocolConfig.
func (in *ModbusProtocolConfig) DeepCopy() *ModbusProtocolConfig {
	if in == nil {
		return nil
	}
	out := new(ModbusProtocolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertyVisitor) DeepCopyInto(out *PropertyVisitor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertyVisitor.
func (in *PropertyVisitor) DeepCopy() *PropertyVisitor {
	if in == nil {
		return nil
	}
	out := new(PropertyVisitor)
	in.DeepCopyInto(out)
	return out
}
