// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package api

import (
	"github.com/rancher/octopus/api/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTClientBasicAuth) DeepCopyInto(out *MQTTClientBasicAuth) {
	*out = *in
	if in.UsernameRef != nil {
		in, out := &in.UsernameRef, &out.UsernameRef
		*out = new(v1alpha1.DeviceLinkReferenceRelationship)
		**out = **in
	}
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(v1alpha1.DeviceLinkReferenceRelationship)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTClientBasicAuth.
func (in *MQTTClientBasicAuth) DeepCopy() *MQTTClientBasicAuth {
	if in == nil {
		return nil
	}
	out := new(MQTTClientBasicAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTClientOptions) DeepCopyInto(out *MQTTClientOptions) {
	*out = *in
	if in.ProtocolVersion != nil {
		in, out := &in.ProtocolVersion, &out.ProtocolVersion
		*out = new(uint)
		**out = **in
	}
	if in.BasicAuth != nil {
		in, out := &in.BasicAuth, &out.BasicAuth
		*out = new(MQTTClientBasicAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.TLSConfig != nil {
		in, out := &in.TLSConfig, &out.TLSConfig
		*out = new(MQTTClientTLS)
		(*in).DeepCopyInto(*out)
	}
	if in.CleanSession != nil {
		in, out := &in.CleanSession, &out.CleanSession
		*out = new(bool)
		**out = **in
	}
	if in.Store != nil {
		in, out := &in.Store, &out.Store
		*out = new(MQTTClientStore)
		**out = **in
	}
	if in.ResumeSubs != nil {
		in, out := &in.ResumeSubs, &out.ResumeSubs
		*out = new(bool)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.KeepAlive != nil {
		in, out := &in.KeepAlive, &out.KeepAlive
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PingTimeout != nil {
		in, out := &in.PingTimeout, &out.PingTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = new(bool)
		**out = **in
	}
	if in.WriteTimeout != nil {
		in, out := &in.WriteTimeout, &out.WriteTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.WaitTimeout != nil {
		in, out := &in.WaitTimeout, &out.WaitTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DisconnectQuiesce != nil {
		in, out := &in.DisconnectQuiesce, &out.DisconnectQuiesce
		*out = new(v1.Duration)
		**out = **in
	}
	if in.AutoReconnect != nil {
		in, out := &in.AutoReconnect, &out.AutoReconnect
		*out = new(bool)
		**out = **in
	}
	if in.MaxReconnectInterval != nil {
		in, out := &in.MaxReconnectInterval, &out.MaxReconnectInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MessageChannelDepth != nil {
		in, out := &in.MessageChannelDepth, &out.MessageChannelDepth
		*out = new(uint)
		**out = **in
	}
	if in.HTTPHeaders != nil {
		in, out := &in.HTTPHeaders, &out.HTTPHeaders
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTClientOptions.
func (in *MQTTClientOptions) DeepCopy() *MQTTClientOptions {
	if in == nil {
		return nil
	}
	out := new(MQTTClientOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTClientTLS) DeepCopyInto(out *MQTTClientTLS) {
	*out = *in
	if in.CAFilePEMRef != nil {
		in, out := &in.CAFilePEMRef, &out.CAFilePEMRef
		*out = new(v1alpha1.DeviceLinkReferenceRelationship)
		**out = **in
	}
	if in.CertFilePEMRef != nil {
		in, out := &in.CertFilePEMRef, &out.CertFilePEMRef
		*out = new(v1alpha1.DeviceLinkReferenceRelationship)
		**out = **in
	}
	if in.KeyFilePEMRef != nil {
		in, out := &in.KeyFilePEMRef, &out.KeyFilePEMRef
		*out = new(v1alpha1.DeviceLinkReferenceRelationship)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTClientTLS.
func (in *MQTTClientTLS) DeepCopy() *MQTTClientTLS {
	if in == nil {
		return nil
	}
	out := new(MQTTClientTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTMessageOptions) DeepCopyInto(out *MQTTMessageOptions) {
	*out = *in
	in.MQTTMessagePayloadOptions.DeepCopyInto(&out.MQTTMessagePayloadOptions)
	in.MQTTMessageTopicOperation.DeepCopyInto(&out.MQTTMessageTopicOperation)
	if in.Will != nil {
		in, out := &in.Will, &out.Will
		*out = new(MQTTWillMessage)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTMessageOptions.
func (in *MQTTMessageOptions) DeepCopy() *MQTTMessageOptions {
	if in == nil {
		return nil
	}
	out := new(MQTTMessageOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTMessagePayloadOptions) DeepCopyInto(out *MQTTMessagePayloadOptions) {
	*out = *in
	if in.QoS != nil {
		in, out := &in.QoS, &out.QoS
		*out = new(MQTTMessageQoSLevel)
		**out = **in
	}
	if in.Retained != nil {
		in, out := &in.Retained, &out.Retained
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTMessagePayloadOptions.
func (in *MQTTMessagePayloadOptions) DeepCopy() *MQTTMessagePayloadOptions {
	if in == nil {
		return nil
	}
	out := new(MQTTMessagePayloadOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTMessageTopicOperation) DeepCopyInto(out *MQTTMessageTopicOperation) {
	*out = *in
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(MQTTMessageTopicOperator)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTMessageTopicOperation.
func (in *MQTTMessageTopicOperation) DeepCopy() *MQTTMessageTopicOperation {
	if in == nil {
		return nil
	}
	out := new(MQTTMessageTopicOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTMessageTopicOperator) DeepCopyInto(out *MQTTMessageTopicOperator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTMessageTopicOperator.
func (in *MQTTMessageTopicOperator) DeepCopy() *MQTTMessageTopicOperator {
	if in == nil {
		return nil
	}
	out := new(MQTTMessageTopicOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTOptions) DeepCopyInto(out *MQTTOptions) {
	*out = *in
	in.Client.DeepCopyInto(&out.Client)
	in.Message.DeepCopyInto(&out.Message)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTOptions.
func (in *MQTTOptions) DeepCopy() *MQTTOptions {
	if in == nil {
		return nil
	}
	out := new(MQTTOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTWillMessage) DeepCopyInto(out *MQTTWillMessage) {
	*out = *in
	in.Content.DeepCopyInto(&out.Content)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTWillMessage.
func (in *MQTTWillMessage) DeepCopy() *MQTTWillMessage {
	if in == nil {
		return nil
	}
	out := new(MQTTWillMessage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTWillMessageContent) DeepCopyInto(out *MQTTWillMessageContent) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTWillMessageContent.
func (in *MQTTWillMessageContent) DeepCopy() *MQTTWillMessageContent {
	if in == nil {
		return nil
	}
	out := new(MQTTWillMessageContent)
	in.DeepCopyInto(out)
	return out
}
