// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/rancher/octopus/pkg/mqtt/api/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceExtensionSpec) DeepCopyInto(out *DeviceExtensionSpec) {
	*out = *in
	if in.MQTT != nil {
		in, out := &in.MQTT, &out.MQTT
		*out = new(apiv1alpha1.MQTTOptionsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceExtensionSpec.
func (in *DeviceExtensionSpec) DeepCopy() *DeviceExtensionSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceExtensionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceExtensionStatus) DeepCopyInto(out *DeviceExtensionStatus) {
	*out = *in
	if in.MQTT != nil {
		in, out := &in.MQTT, &out.MQTT
		*out = new(apiv1alpha1.MQTTOptionsStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceExtensionStatus.
func (in *DeviceExtensionStatus) DeepCopy() *DeviceExtensionStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceExtensionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DummyProtocolDevice) DeepCopyInto(out *DummyProtocolDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DummyProtocolDevice.
func (in *DummyProtocolDevice) DeepCopy() *DummyProtocolDevice {
	if in == nil {
		return nil
	}
	out := new(DummyProtocolDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DummyProtocolDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DummyProtocolDeviceList) DeepCopyInto(out *DummyProtocolDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DummyProtocolDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DummyProtocolDeviceList.
func (in *DummyProtocolDeviceList) DeepCopy() *DummyProtocolDeviceList {
	if in == nil {
		return nil
	}
	out := new(DummyProtocolDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DummyProtocolDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DummyProtocolDeviceProtocol) DeepCopyInto(out *DummyProtocolDeviceProtocol) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DummyProtocolDeviceProtocol.
func (in *DummyProtocolDeviceProtocol) DeepCopy() *DummyProtocolDeviceProtocol {
	if in == nil {
		return nil
	}
	out := new(DummyProtocolDeviceProtocol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DummyProtocolDeviceSpec) DeepCopyInto(out *DummyProtocolDeviceSpec) {
	*out = *in
	in.Extension.DeepCopyInto(&out.Extension)
	out.Protocol = in.Protocol
	if in.Props != nil {
		in, out := &in.Props, &out.Props
		*out = make(map[string]DummyProtocolDeviceSpecProps, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DummyProtocolDeviceSpec.
func (in *DummyProtocolDeviceSpec) DeepCopy() *DummyProtocolDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(DummyProtocolDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DummyProtocolDeviceSpecObjectOrArrayProps) DeepCopyInto(out *DummyProtocolDeviceSpecObjectOrArrayProps) {
	*out = *in
	in.DummyProtocolDeviceSpecProps.DeepCopyInto(&out.DummyProtocolDeviceSpecProps)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DummyProtocolDeviceSpecObjectOrArrayProps.
func (in *DummyProtocolDeviceSpecObjectOrArrayProps) DeepCopy() *DummyProtocolDeviceSpecObjectOrArrayProps {
	if in == nil {
		return nil
	}
	out := new(DummyProtocolDeviceSpecObjectOrArrayProps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DummyProtocolDeviceSpecProps) DeepCopyInto(out *DummyProtocolDeviceSpecProps) {
	*out = *in
	if in.ArrayProps != nil {
		in, out := &in.ArrayProps, &out.ArrayProps
		*out = new(DummyProtocolDeviceSpecObjectOrArrayProps)
		(*in).DeepCopyInto(*out)
	}
	if in.ObjectProps != nil {
		in, out := &in.ObjectProps, &out.ObjectProps
		*out = make(map[string]DummyProtocolDeviceSpecObjectOrArrayProps, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DummyProtocolDeviceSpecProps.
func (in *DummyProtocolDeviceSpecProps) DeepCopy() *DummyProtocolDeviceSpecProps {
	if in == nil {
		return nil
	}
	out := new(DummyProtocolDeviceSpecProps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DummyProtocolDeviceStatus) DeepCopyInto(out *DummyProtocolDeviceStatus) {
	*out = *in
	if in.Extension != nil {
		in, out := &in.Extension, &out.Extension
		*out = new(DeviceExtensionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Props != nil {
		in, out := &in.Props, &out.Props
		*out = make(map[string]DummyProtocolDeviceStatusProps, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DummyProtocolDeviceStatus.
func (in *DummyProtocolDeviceStatus) DeepCopy() *DummyProtocolDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(DummyProtocolDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DummyProtocolDeviceStatusObjectOrArrayProps) DeepCopyInto(out *DummyProtocolDeviceStatusObjectOrArrayProps) {
	*out = *in
	in.DummyProtocolDeviceStatusProps.DeepCopyInto(&out.DummyProtocolDeviceStatusProps)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DummyProtocolDeviceStatusObjectOrArrayProps.
func (in *DummyProtocolDeviceStatusObjectOrArrayProps) DeepCopy() *DummyProtocolDeviceStatusObjectOrArrayProps {
	if in == nil {
		return nil
	}
	out := new(DummyProtocolDeviceStatusObjectOrArrayProps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DummyProtocolDeviceStatusProps) DeepCopyInto(out *DummyProtocolDeviceStatusProps) {
	*out = *in
	if in.IntValue != nil {
		in, out := &in.IntValue, &out.IntValue
		*out = new(int)
		**out = **in
	}
	if in.StringValue != nil {
		in, out := &in.StringValue, &out.StringValue
		*out = new(string)
		**out = **in
	}
	if in.FloatValue != nil {
		in, out := &in.FloatValue, &out.FloatValue
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.BooleanValue != nil {
		in, out := &in.BooleanValue, &out.BooleanValue
		*out = new(bool)
		**out = **in
	}
	if in.ArrayValue != nil {
		in, out := &in.ArrayValue, &out.ArrayValue
		*out = make([]DummyProtocolDeviceStatusObjectOrArrayProps, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ObjectValue != nil {
		in, out := &in.ObjectValue, &out.ObjectValue
		*out = make(map[string]DummyProtocolDeviceStatusObjectOrArrayProps, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DummyProtocolDeviceStatusProps.
func (in *DummyProtocolDeviceStatusProps) DeepCopy() *DummyProtocolDeviceStatusProps {
	if in == nil {
		return nil
	}
	out := new(DummyProtocolDeviceStatusProps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DummySpecialDevice) DeepCopyInto(out *DummySpecialDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DummySpecialDevice.
func (in *DummySpecialDevice) DeepCopy() *DummySpecialDevice {
	if in == nil {
		return nil
	}
	out := new(DummySpecialDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DummySpecialDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DummySpecialDeviceList) DeepCopyInto(out *DummySpecialDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DummySpecialDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DummySpecialDeviceList.
func (in *DummySpecialDeviceList) DeepCopy() *DummySpecialDeviceList {
	if in == nil {
		return nil
	}
	out := new(DummySpecialDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DummySpecialDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DummySpecialDeviceProtocol) DeepCopyInto(out *DummySpecialDeviceProtocol) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DummySpecialDeviceProtocol.
func (in *DummySpecialDeviceProtocol) DeepCopy() *DummySpecialDeviceProtocol {
	if in == nil {
		return nil
	}
	out := new(DummySpecialDeviceProtocol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DummySpecialDeviceSpec) DeepCopyInto(out *DummySpecialDeviceSpec) {
	*out = *in
	in.Extension.DeepCopyInto(&out.Extension)
	out.Protocol = in.Protocol
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DummySpecialDeviceSpec.
func (in *DummySpecialDeviceSpec) DeepCopy() *DummySpecialDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(DummySpecialDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DummySpecialDeviceStatus) DeepCopyInto(out *DummySpecialDeviceStatus) {
	*out = *in
	if in.Extension != nil {
		in, out := &in.Extension, &out.Extension
		*out = new(DeviceExtensionStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DummySpecialDeviceStatus.
func (in *DummySpecialDeviceStatus) DeepCopy() *DummySpecialDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(DummySpecialDeviceStatus)
	in.DeepCopyInto(out)
	return out
}
