apiVersion: edge.cattle.io/v1alpha1
kind: DeviceLink
metadata:
  name: thermometer-rtu
spec:
  adaptor:
    node: edge-worker
    name: adaptors.edge.cattle.io/modbus
  model:
    apiVersion: "devices.edge.cattle.io/v1alpha1"
    kind: "ModbusDevice"
  template:
    metadata:
      labels:
        device: modbus-rtu
    spec:
      parameters:
        syncInterval: 15s
        timeout: 10s
      protocol:
        rtu:
          # replace the serial port if needed
          endpoint: /dev/ttyS001
          workerID: 1
          parity: "N"
          stopBits: 2
          dataBits: 8
          baudRate: 19200
      properties:
        - name: temperature
          description: temperature value, the source is in kevin degree.
          readOnly: true
          visitor:
            register: HoldingRegister
            offset: 0
            quantity: 2
            orderOfOperations:
              # the source is kevin temperature,
              # change to celsius degree.
              - type: Subtract
                value: "273.15"
          type: float
        - name: humidity-percent
          description: humidity value, the source is relative humidity.
          readOnly: true
          visitor:
            register: HoldingRegister
            offset: 2
            quantity: 2
          type: float
        - name: temperature-limitation
          description: the limiation of temperature value.
          readOnly: false
          visitor:
            register: HoldingRegister
            offset: 4
            quantity: 2
          type: int
        - name: hight-temperature-alarm
          description: reports alarm if the temperature reaches temperature-limitation.
          readOnly: true
          visitor:
            register: CoilRegister
            offset: 0
            quantity: 1
          type: boolean
