apiVersion: edge.cattle.io/v1alpha1
kind: DeviceLink
metadata:
  name: simulate-thermometer
spec:
  adaptor:
    node: edge-worker
    name: adaptors.edge.cattle.io/modbus
  model:
    apiVersion: "devices.edge.cattle.io/v1alpha1"
    kind: "ModbusDevice"
  template:
    metadata:
      labels:
        device: modbus-rtu
    spec:
      protocol:
        rtu:
          # replace the serial port if needed
          endpoint: /dev/ttyS001
          workerID: 1
          parity: "N"
          stopBits: 2
          dataBits: 8
          baudRate: 19200
          syncInterval: 15s
      properties:
        - name: switch
          description: switch to mock or not.
          type: boolean
          accessModes:
            - WriteMany
            - ReadOnce
          visitor:
            register: CoilRegister
            offset: 1
            quantity: 1
        - name: temperature
          description: temperature value, the source is in kevin degree.
          type: float
          accessModes:
            - ReadMany
          visitor:
            register: HoldingRegister
            offset: 0
            quantity: 2
            arithmeticOperations:
              # the source is kevin temperature,
              # change to celsius degree.
              - type: Subtract
                value: "273.15"
        - name: humidity-percent
          description: humidity value, the source is relative humidity.
          type: float
          accessModes:
            - ReadMany
          visitor:
            register: HoldingRegister
            offset: 2
            quantity: 2
        - name: temperature-limitation
          description: the limiation of temperature value.
          type: int
          accessModes:
            - ReadOnce
            - WriteOnce
          visitor:
            register: HoldingRegister
            offset: 4
            quantity: 2
        - name: hight-temperature-alarm
          description: reports alarm if the temperature reaches temperature-limitation.
          type: boolean
          accessModes:
            - ReadMany
          visitor:
            register: CoilRegister
            offset: 0
            quantity: 1
        - name: battery
          description: the battery of thermometer.
          type: int8
          accessModes:
            - ReadMany
          visitor:
            register: HoldingRegister
            offset: 6
            quantity: 1
        - name: manufacturer
          description: the manufacturer of temperature value.
          type: string
          accessModes:
            - ReadOnce
          visitor:
            register: HoldingRegister
            offset: 7
            quantity: 56
