apiVersion: edge.cattle.io/v1alpha1
kind: DeviceLink
metadata:
  name: modbus-rtu
spec:
  adaptor:
    node: edge-worker
    name: adaptors.edge.cattle.io/modbus
  model:
    apiVersion: "devices.edge.cattle.io/v1alpha1"
    kind: "ModbusDevice"
  template:
    metadata:
      labels:
        device: modbus-rtu
    spec:
      parameters:
        syncInterval: 10s
        timeout: 10s
      protocol:
        rtu:
          endpoint: /dev/tty.usbserial-1410
          workerID: 1
          parity: "N"
          stopBits: 1
          dataBits: 8
          baudRate: 9600
      properties:
        - name: temperature
          description: data collection of temperature sensor
          readOnly: true
          visitor:
            register: HoldingRegister
            offset: 0
            quantity: 1
            orderOfOperations:
              - type: Divide
                value: "10"
          type: float
