apiVersion: edge.cattle.io/v1alpha1
kind: DeviceLink
metadata:
  name: thermometer-tcp
spec:
  adaptor:
    node: edge-worker
    name: adaptors.edge.cattle.io/modbus
  model:
    apiVersion: "devices.edge.cattle.io/v1alpha1"
    kind: "ModbusDevice"
  template:
    metadata:
      labels:
        device: modbus-tcp
    spec:
      parameters:
        syncInterval: 15s
      protocol:
        tcp:
          # replace the ip:port address if needed
          endpoint: octopus-simulator-modbus-tcp.octopus-simulator-system:5020
          workerID: 1
      properties:
        - name: temperature
          description: temperature value, the source is in kevin degree.
          readOnly: true
          visitor:
            register: HoldingRegister
            offset: 0
            quantity: 2
            orderOfOperations:
              # the source is kevin temperature,
              # change to celsius degree.
              - type: Subtract
                value: "273.15"
          type: float
        - name: humidity-percent
          description: humidity value, the source is relative humidity.
          readOnly: true
          visitor:
            register: HoldingRegister
            offset: 2
            quantity: 2
          type: float
        - name: temperature-limitation
          description: the limiation of temperature value.
          readOnly: false
          visitor:
            register: HoldingRegister
            offset: 4
            quantity: 2
          type: int
        - name: hight-temperature-alarm
          description: reports alarm if the temperature reaches temperature-limitation.
          readOnly: true
          visitor:
            register: CoilRegister
            offset: 0
            quantity: 1
          type: boolean
