apiVersion: edge.cattle.io/v1alpha1
kind: DeviceLink
metadata:
  name: modbus-tcp
spec:
  adaptor:
    node: edge-worker
    name: adaptors.edge.cattle.io/modbus
  model:
    apiVersion: "devices.edge.cattle.io/v1alpha1"
    kind: "ModbusDevice"
  template:
    metadata:
      labels:
        device: modbus-tcp
    spec:
      extension:
        mqtt:
          client:
            server: tcp://test.mosquitto.org:1883
          message:
            # uses dynamic topic with namespaced name
            topic: "cattle.io/octopus/:namespace/:name"
      parameters:
        syncInterval: 15s
        timeout: 10s
      protocol:
        tcp:
          # replace the ip:port address if needed
          endpoint: 192.168.1.3:5020
          workerID: 1
      properties:
        - name: temperature
          description: temperature value, should be divided by 10
          readOnly: true
          visitor:
            register: HoldingRegister
            offset: 0
            quantity: 1
            orderOfOperations:
              - type: Divide
                value: "10"
          type: float
        - name: humidity
          description: humidity value, should be divided by 10
          readOnly: true
          visitor:
            register: HoldingRegister
            offset: 1
            quantity: 1
            orderOfOperations:
              - type: Divide
                value: "10"
          type: float
        - name: alert
          description: the value reaches alert limitation
          readOnly: true
          visitor:
            register: CoilRegister
            offset: 0
            quantity: 1
          type: boolean
        - name: limitation
          description: the limitation
          readOnly: false
          value: "20"
          visitor:
            register: HoldingRegister
            offset: 5
            quantity: 1
            orderOfOperations:
              - type: Divide
                value: "10"
          type: float
